name: Deploy to Lightsail

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Private Docker Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} --password-stdin

      - name: Build and Push Docker Images
        run: |
          VERSION=$(git rev-parse --short HEAD)
          docker build -t ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_ALIAS }}:$VERSION .
          docker tag ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_ALIAS }}:$VERSION ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_ALIAS }}:latest
          docker push ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_ALIAS }}:$VERSION
          docker push ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_ALIAS }}:latest

      - name: Notify server to deploy
        run: |
          VERSION=$(git rev-parse --short HEAD)
          curl -X POST https://${{ secrets.REGISTRY_URL }}/deploy/github-actions-deploy \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.AUTHORIZATION_REGISTRY_TOKEN }}" \
            -d '{
                "service_name": "'"${{ secrets.SERVICE_NAME }}"'",
                "image_alias": "'"${{ secrets.IMAGE_ALIAS }}"'",
                "tag": "'"$VERSION"'"
            }'
